### ISSUE TITLE
[Feature request] Filtering .desktop files

### ISSUE THREAD

**Issue by emdicmanel** [jgmenu/jgmenu#182]
First of all, great software :-) 

It would be nice to have some kind of filtering in order to avoid some entries. My case: I have 3 desktop enviroments (Cinnamon, Mate and Openbox), and when using Openbox, for instance, jgmenu creates a menu with all the Cinnamon and Mate apps included, with a huge and unusable menu as a result.

I've tried "jgmenu_run hide-app xx.desktop", but this creates a .desktop file in the user .local/share/applications, making the app invisible not only for jgmenu but all enviroments.

It would be possible some "--not include STRING" or similar?

Thank you for your time.

**Comment by johanmalm** [comment]
Thank you.

As a starting point I prefer not to add more options to the jgmenu-apps.c module because I want to avoid growing into xdg-menu spec in the long term.

There are two important aspects of the `jgmenu` design which I think will help here:

1. It has a modular architecture where the content is piped to the UI
2. The CSV syntax ensures one entry per line - which is quite handy for command line bashing.

Would the following work?

```
jgmenu_run apps | grep -iv string1 | jgmenu --simple
```

In your `~/.config/jgmenu/jgmenurc` you can simple set `csv_cmd = jgmenu_run apps | grep -iv whatever`

You can filter out multiple strings by `grep -iv 'foo\|bar\|baz'`

Alternatively, the jgmenu-lx.c module is xdg-menu spec compliant so you could design a .menu file that excludes specific entries (I can't quite remember how, but it's just a matter of reading the the xdg menu spec).

**Comment by emdicmanel** [comment]
Impressive. I didn't realize the power of `csv_cmd`. Works great applying it in `~/.config/jgmenu/jgmenurc`, although there is no change if I try it in the shell. Anyway, solved :+1: 

Yes, I considered the `lx` module, but I read that does not parse right some `.menu` files (xfce, I believe). I've not found a lot of documentation about this option, so I decided to write here.

Thank you for your fast and useful answer. Keep up the great work!
