### ISSUE TITLE
CSV flavour is not CSV

### ISSUE THREAD

**Issue by yecril23pl** [jgmenu/jgmenu#219]
Suppose your `prepend.csv` contains the following line:

    "Uruchom…",gmrun,system-run

Then the resulting command label will be quoted: **"Uruchom…"**.

If you load the file `prepend.csv` into [Calc](https://help.libreoffice.org/7.4/en-US/text/scalc/guide/csv_files.html?&DbPAR=CALC&System=UNIX) using default import settings, the label column will be `Uruchom…` (without quotes) as expected.

Therefore, the file format is not a CSV flavor and should not be documented as such.

**Comment by johanmalm** [comment]
It is a CSV flavour. See https://en.wikipedia.org/wiki/Comma-separated_values#Standardization

If variations from standards were not allowed, then the C used in Linux would not be C and the markdown used by github would not be markdown.

We don't resolve double quotes because it helps flexibility with writing commands in the exec fields.
If you want to quote, use three double quotes `"""`.
